#!/usr/bin/env bash
# This script displays a clock
h=0
while [ $h -le 12 ]
do
      echo "Hour: $h"
      m=1
      while [ $m -lt 60 ]
      do
              echo $m
              ((m++))
      done
      ((h++))
done
