#!/usr/bin/env bash
# Script to install nginx to our server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
