#!/usr/bin/env bash
# Script that configure server with a custom HTTP header

# Updating packages before installation
sudo apt-get -y update
sudo apt-get -y install nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a moved permanent redirection (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/magnifiscence permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Creating a 404 custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Creating an HTTP response header
sudo sed -i "server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing configrations for syntax error
sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart
