#!/usr/bin/env bash
# install nginx

# configure haproxy
sudo apt update -y
sudo apt-get -y install haproxy

haproxy_config="
frontend my_web
        bind *:80
	mode http
        default_backend my_web_backend

backend my_web_backend
        server 372906-web-01 34.224.62.101 check
        server 372906-web-02 54.165.41.74 check"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

#Start haproxy
sudo service haproxy restart
