#!/usr/bin/env bash
# install nginx

# configure haproxy
sudo apt update -y
sudo apt-get -y install haproxy

haproxy_config="
frontend my_web
        bind *:80
        default_backend my_web_backend

backend my_web_backend
        server 346350-web-01 54.87.172.227:80 check
        server 346350-web-02 100.26.164.133:80 check"

sudo echo "$haproxy_config" >> /etc/haproxy/haproxy.cfg

#Start haproxy
sudo service haproxy restart
