#!/usr/bin/env bash
# This script is displaying "Best School 10x and Hi for the 9th iteration

i=0

while [ $i -lt 10 ]
do
     echo "Best School"
     if [ $i == 8 ]
     then
          echo "Best School"
          echo "Hi"
     fi
     ((i++))
done
