#!/usr/bin/env bash
#Configuring a ufw to block all incoming traffic except
for tcp port 22, 80 and 443 and allow all outgoing traffic.

sudo apt-get update
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw status verbose
sudo ufw enable
sudo ufw status verbose
