#!/usr/bin/env bash
# Gracefully reloads gunicorn

# Define the path to the Gunicorn PID file
PID_FILE="/path/to/gunicorn.pid"

# Check if the PID file exists
if [ -f "$PID_FILE" ]; then
    echo "Reloading Gunicorn"
    # Send the HUP signal to the Gunicorn master process
    kill -HUP $(cat "$PID_FILE")
    echo "Gunicorn reloaded successfully."
else
    echo "Gunicorn PID file not found. Is Gunicorn running?"
fi
